apiVersion: v2
appVersion: 7.11.24
description: Embed powerful analytics inside your apps and turn your customers into
  success stories with built-in intelligence features.
home: https://www.boldbi.com/
icon: https://website-assets.boldbi.com/wp-content/uploads/2019/05/boldbi-header-menu-logo.svg
name: boldbi
type: application
version: 7.11.24
