apiVersion: v2
name: bold-common
type: application
appVersion: 5.2.48
version: 5.2.48
description: Embed powerful analytics inside your apps and turn your customers into success stories with built-in intelligence features.
home: https://www.boldbi.com/
icon: https://website-assets.boldbi.com/wp-content/uploads/2019/05/boldbi-header-menu-logo.svg
