{{- range $service := .Values.instanceConfig}}
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: {{ $.Chart.Name }}_{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ $service.app }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- if $.Chart.AppVersion }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  name: {{ $service.app }}-service
  {{- if eq $.Release.Namespace "default" }}
  namespace: {{ $.Values.namespace.name }}
  {{- else }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
  - name: {{ $service.app }}-port
    {{- if eq $service.app "id-web" }}
    port: 6000
    {{- else if eq $service.app "id-api" }}
    port: 6001
    {{- else if eq $service.app "id-ums" }}
    port: 6002
    {{- else if eq $service.app "bi-web" }}
    port: 6004
    {{- else if eq $service.app "bi-api" }}
    port: 6005
    {{- else if eq $service.app "bi-jobs" }}
    port: 6006
    {{- else if eq $service.app "bi-dataservice" }}
    port: 6007
    {{- else if eq $service.app "bold-etl" }}
    port: 6009
    {{- else if eq $service.app "reports-web" }}
    port: 6550
    {{- else if eq $service.app "reports-api" }}
    port: 6551
    {{- else if eq $service.app "reports-jobs" }}
    port: 6552
    {{- else if eq $service.app "reports-reportservice" }}
    port: 6553
    {{- else if eq $service.app "reports-viewer" }}
    port: 6554
    {{- end }}
    targetPort: {{ $.Values.service.port }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ $service.app }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
---
{{- end }}