apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: <Enter-gateway-name>
  namespace: <Enter-gateway-namespace>
  annotations:
    alb.networking.azure.io/alb-namespace: <Enter-your-alb-name>
    alb.networking.azure.io/alb-name: <Enter-your-alb-namespace>
spec:
  gatewayClassName: azure-alb-external
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  # - name: https
  #   protocol: HTTPS
  #   port: 443
  #   tls:
  #     mode: Terminate
  #     certificateRefs:
  #     - name:  <Enter-your-tls-create-name>
