
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-urls-config
  namespace: bold-services
data:
  ID_WEB_SERVICE_URL: http://id-web-service:6000
  ID_API_SERVICE_URL: http://id-api-service:6001/api
  ID_UMS_SERVICE_URL: http://id-ums-service:6002/ums
  BI_WEB_SERVICE_URL: http://bi-web-service:6004/bi
  BI_API_SERVICE_URL: http://bi-api-service:6005/bi/api
  BI_JOBS_SERVICE_URL: http://bi-jobs-service:6006/bi/jobs
  BI_DESIGNER_SERVICE_URL: http://bi-dataservice-service:6007/bi/designer
  BI_DESIGNER_HELPER_SERVICE_URL: http://bi-dataservice-service:6007/bi/designer/helper
  BOLD_ETL_SERVICE_URL: http://bold-etl-service:6009
  BOLD_ETL_BLAZOR_SERVICE_URL: http://bold-etl-service:6009/framework/blazor.server.js
  BOLD_AI_SERVICE_URL: http://bold-ai-service:6010/aiservice
  REPORTS_WEB_SERVICE_URL: http://reports-web-service:6550/reporting
  REPORTS_API_SERVICE_URL: http://reports-api-service:6551/reporting/api
  REPORTS_JOBS_SERVICE_URL: http://reports-jobs-service:6552/reporting/jobs
  REPORTS_DESIGNER_SERVICE_URL: http://reports-reportservice-service:6553/reporting/reportservice
  REPORTS_VIEWER_SERVICE_URL: http://reports-viewer-service:6554/reporting/viewer